language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
before_script:
  - pip install -r requirements-test.txt
  - python setup.py develop
script:
  - pytest --cov SOC
