language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
before_script:
  - pip install -r requirements-test.txt
  - python setup.py develop
script:
  - pytest --cov SOC
after_success:
  - codecov

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFN0YW5jemFrRG9taW5payUzQW1hdHJpeC5vcmcvJTIxQVJIZURXQ0JHQkp4VlZ5RFNrJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
